### ISSUE TITLE
Feedback to middleware concept

### ISSUE THREAD

**Issue by andywer** [Legitcode/legible#26]
Hey guys!

I like the idea behind legible and would like to give some feedback about the proposed [middleware concept](https://github.com/Legitcode/legible/blob/master/README.md#middleware).

I think being able to write a middleware can be quite a useful gimmick, but I'd also like to share a concern about mutating the main `request` (the default export) using `request.middleware()`.

It looks like `request.middleware()` is supposed to register a globally applied middleware, it is not supposed to return a new `request` tag, right? This could potentially break a lot of stuff.

But maybe I got the wrong idea about it, it seems to be just a draft as of now. Just want to make sure you see the potential footgun on the horizon :)

**Comment by andywer** [comment]
(Completed the issue description. That's what happens when you write issues on your iPhone... 🙈😅)

**Comment by zackify** [comment]
I really need to update the readme. There isn't really a need for middleware anymore since I have added onUrl, onResponse, etc. I do agree this could be better though. If you have any questions I can show you code samples on how to do things. I am using this in production and it's been really nice! Instead of middleware, think about composing partials.

**Comment by andywer** [comment]
Yeah, that does sound better ^^

Cool. I don't have a real use case for it right now, but will keep it in mind 😉

**Comment by zackify** [comment]
Okay, let me know if you need anything! I guess you can close this unless if you need anything specific.

**Comment by andywer** [comment]
Sure
